name: Shark AI Automated

on:
  schedule:
    - cron: '0 13-19 * * *'  # 20h - 02h VN
  workflow_dispatch:        # Nút bấm Manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run Shark AI
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python SharkAPI.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Shark-Bot-Automated"
          git config --global user.email "pnstung@gmail.com"
          git add shark_history_log.csv odds_tracker.csv
          git commit -m "Shark update [skip ci]" || exit 0
          git push
