name: Shark AI 24/7
on:
  schedule:
    - cron: '0 * * * *' # Chạy tự động mỗi tiếng
  workflow_dispatch: # Nút chạy bằng tay

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Libs
        run: pip install requests pandas
      - name: Execute Shark
        run: python SharkAPI.py
      - name: Sync Data
        run: |
          git config --global user.name 'Shark-AI'
          git config --global user.email 'bot@shark.ai'
          git add shark_memory.csv
          git commit -m "Update History [skip ci]" || echo "No changes"
          git push
