name: Shark AI 24/7
on:
  schedule:
    - cron: '0 * * * *' # Quét kèo mỗi tiếng
    - cron: '0 1 * * *' # 8h sáng VN check HÚP/GÃY
  workflow_dispatch:
jobs:
  run-shark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: pip install requests pandas
      - name: Scanner
        run: python SharkAPI.py
      - name: Checker
        run: python Shark_Checker.py
      - name: Save Memory
        run: |
          git config --global user.name 'Shark-AI'
          git config --global user.email 'shark@ai.com'
          git add shark_memory.csv
          git commit -m "Update Memory [skip ci]" || echo "No changes"
          git push
