name: Shark AI Automated

on:
  schedule:
    - cron: '0 13-20 * * *'  # Chạy mỗi tiếng từ 20h đến 02h sáng (Giờ VN)
  workflow_dispatch:        # Nút bấm quét tay thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run Shark AI
          # Đảm bảo tên file SharkAPI.py trùng với file code của Idol
        run: python SharkAPI.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Shark-Bot-Automated"
          git config --global user.email "pnstung@gmail.com"
          git add shark_history_log.csv odds_tracker.csv
          git commit -m "Shark update history and memory [skip ci]" || exit 0
          git push
